name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Cypress
      run: npm install cypress

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Run Cypress tests
      run: |
        npx cypress run || echo "Error during Cypress tests"
        # Genera el informe HTML en el directorio de Cypress
        ./generate-report.sh


    - name: Create HTML report artifact
      uses: actions/upload-artifact@v2
      with:
        name: cypress-html-report
        path: cypress-report.html # Ajusta la ruta al informe HTML generado por Cypress

