name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Cypress
      run: npm install cypress

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Run Cypress tests and generate Allure report
      run: |
        npx cypress run --reporter allure --reporter-options "resultsDir=cypress/allure-results"
      working-directory: ${{ github.workspace }}

    - name: Create Allure report artifact
      run: |
        allure generate cypress/allure-results --clean -o cypress/allure-report
        cd cypress
        zip -r allure-report.zip allure-report
      working-directory: ${{ github.workspace }}

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: cypress/allure-report.zip

    - name: Generate Cucumber HTML Report
      run: |
        npm install cucumber-html-report
        npx cucumber-html-report -o cypress/cucumber-report/cucumber.html -i cypress/cucumber-report/cucumber.json
      working-directory: ${{ github.workspace }}

    - name: Create Cucumber HTML Report artifact
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-html-report
        path: cypress/cucumber-report/cucumber.html

    - name: Create Jekyll site artifact
      uses: actions/upload-artifact@v2
      with:
        name: jekyll-site
        path: _site

        
        
